FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04

RUN pip install --upgrade 'python==3.10'
RUN pip install --upgrade 'transformers==4.25.1'
RUN pip install --upgrade 'datasets==2.7.1'
RUN pip install --upgrade 'seqeval'